### ISSUE TITLE
Error in an example (Kotlin basics, part 5)

### ISSUE THREAD

**Issue by AntonKosov** [google-developer-training/kotlin-bootcamp#1]
**Describe the problem**
There is a wrong example on [this page](https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-basics/#4).

**In which step of the codelab can this issue be found?**
Step number 2.

**Versions**
IntelliJ IDEA 2019.2

**Additional information**
The problem is in the following line:
`println(Arrays.toString(array))`
It should be `println(java.util.Arrays.toString(array))`; otherwise, there is an error `error: unresolved reference: Array`.

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Fixed. Thanks for catching that!
