### ISSUE TITLE
Kotlin Bootcamp issue: 5.1: Extensions, 3. Task: Comprehend collections, 

### ISSUE THREAD

**Issue by gmb55** [google-developer-training/kotlin-bootcamp#10]
**Describe the problem**
There is two times point 4. in Step 1 and Step 2. 

**In which step of the codelab can this issue be found?**
Step 1 and Step 2

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Fixed.
