### ISSUE TITLE
Kotlin Bootcamp issue: Grammar Mistake (2: Kotlin basics Step 1) 

### ISSUE THREAD

**Issue by BvdLind** [google-developer-training/kotlin-bootcamp#11]
**Describe the problem**
I think I found a grammatical mistake in the text.

`Using object wrappers take more memory than storing just a number primitive.`

should be:

`Using object wrappers takes more memory than storing just a number primitive`

**In which step of the codelab can this issue be found?**
This sentence can be found in Kotlin Bootcamp for Programmers 2: Kotlin basics Step 1: Explore numeric operators.

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Fixed.
