### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by dev-prajwal21** [google-developer-training/kotlin-bootcamp#12]
**Describe the problem**
Keyword _**"data"**_ is missing in the section which describes the conciseness of the Kotlin code.

**In which step of the codelab can this issue be found?**
Step 2

**Comment by GeneAndGoogle** [comment]
Where exactly are you suggest "data" should be added? Please include the sentence it would appear in.

**Comment by GeneAndGoogle** [comment]
Fixed.
