### ISSUE TITLE
Incorrect loop result in Kotlin-Bootcamp Lesson 2, Task 5, Step 3, Example 4

### ISSUE THREAD

**Issue by AnmAtAnm** [google-developer-training/kotlin-bootcamp#128]
**Describe the problem**
The example code includes:
```
repeat(2) {
     println("A fish is swimming")
}
```

And the result
```
A fish is swimmingA fish is swimming
```

The strings should have a newline between them from the first call to `println`

**In which step of the codelab can this issue be found?**
Lesson 2, Task 5, Step 3, Example 4

**codelab:** kotlin-bootcamp

**Comment by zsmb13** [comment]
Fixed!
