### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by CristianFarcas** [google-developer-training/kotlin-bootcamp#15]
**Describe the problem**
As far as I can see, when installing the JDK, there is not C:\Program Files\Java\jre1.8.0_x directory created. This is maybe because the JDK includes now the JRE.

**In which step of the codelab can this issue be found?**
Lesson 1  -->  Task 3  -->  Step 3

**Steps to reproduce?**
When installing JDK for Windows.

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Thanks for catching this. Fixed.
