### ISSUE TITLE
Wrong output (Kotlin basics, part 5)

### ISSUE THREAD

**Issue by AntonKosov** [google-developer-training/kotlin-bootcamp#2]
**Describe the problem**
The example of output is wrong on [this page](https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-basics/#4).

```
⇒ 50 bubbles in the water
49 bubbles in the water
A fish is swimmingA fish is swimming
```
The output should be:
```
⇒ 50 bubbles in the water
49 bubbles in the water
A fish is swimming
A fish is swimming
```

**In which step of the codelab can this issue be found?**
Step number 3.

**Versions**
IntelliJ IDEA 2019.2.

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
It's a quirk (bug?) of the IntelliJ REPL -- println() doesn't print a \n as it should. So the output is correct for the sample given:
`repeat(2) {
     println("A fish is swimming")
}`

To get it on separate lines in the REPL, you need:
`repeat(2) {
     println("A fish is swimming\n")
}`
