### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by Asif032000** [google-developer-training/kotlin-bootcamp#21]
**Describe the problem**
A clear and concise description of what the problem is.
Checkboxes are not clickable
**In which step of the codelab can this issue be found?**
Step number.8

**Steps to reproduce?**
What are the steps to reproduce the problem?
just go to step 8
**Versions**
What version of IntelliJ IDEA are you using?
2020.1.1
**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
