### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by ron71** [google-developer-training/kotlin-bootcamp#22]
**Describe the problem**
Not able to select any answer corresponding to the questions. Checkbox are not act.

**In which step of the codelab can this issue be found?**
Step number. Step No - 8

**Steps to reproduce?**
Come to the Step 8  - **Homework** and try selecting the any option.

**Versions**
Community verion

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
