### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by Bharathmp7** [google-developer-training/kotlin-bootcamp#23]
**Describe the problem**
A clear and concise description of what the problem is.
I am not able to choose(answer) the homework assignments  options.

**In which step of the codelab can this issue be found?**
Step number. 1. Get started.

**Steps to reproduce?**
What are the steps to reproduce the problem?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
