### ISSUE TITLE
Kotlin Bootcamp issue: Unable to find "Kotlin/JVM" while creating a new project

### ISSUE THREAD

**Issue by pyarisinghk** [google-developer-training/kotlin-bootcamp#25]
**Describe the problem**
Unable to find "Kotlin/JVM" on the right panel as mentioned in the Codelab. While trying to create a new project, after selecting "Kotlin" on the left panel, unable to find "Kotlin/JVM" on the right panel. 

**In which step of the codelab can this issue be found?**
Step number -5 "Task - Create Hello Kotlin"
https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-introduction/#4

**Steps to reproduce?**
What are the steps to reproduce the problem?
1. Install the latest version of JDK
2. Installed the latest version of IntelliJ Idea and checked for updates
3. Click on create new project. Select "Kotlin" on the left pane.  

**Versions**
What version of IntelliJ IDEA are you using? Version 2020.1.1

**Additional information**

**codelab:** kotlin-bootcamp

![image](https://user-images.githubusercontent.com/18439099/81383641-f3ea5d00-912d-11ea-917f-4432a2110efd.png)

**Comment by pyarisinghk** [comment]
![image](https://user-images.githubusercontent.com/18439099/81383554-d4ebcb00-912d-11ea-8942-d9dbfbb69495.png)

**Comment by GeneAndGoogle** [comment]
Thanks for the report.

In IDEA 2020.1.1, it's now labeled **JVM | IDEA**. I've added a note to the codelab.
