### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by parimal6867** [google-developer-training/kotlin-bootcamp#29]
**Describe the problem**
A clear and concise description of what the problem is.

**In which step of the codelab can this issue be found?**
Step number.

**Steps to reproduce?**
What are the steps to reproduce the problem?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp
Not able to mark or check MCQs

**Comment by GeneAndGoogle** [comment]
See #18
