### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by aalhadsawane** [google-developer-training/kotlin-bootcamp#30]
**Describe the problem**
The homework section of Lesson 1 contains MCQs but they can't be selected.

**In which step of the codelab can this issue be found?**
Lesson 1 > Step 8

**Steps to reproduce?**
What are the steps to reproduce the problem?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
