### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by Ishaan75** [google-developer-training/kotlin-bootcamp#31]
**Describe the problem**
I was not able to attempt the quiz of Kotlin bootcamp.

**In which step of the codelab can this issue be found?**
Step number 8 (Homewok).

**Steps to reproduce?**
What are the steps to reproduce the problem?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
