### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by DevAkash99** [google-developer-training/kotlin-bootcamp#33]
**Describe the problem**
In Kotlin Bootcamp for Programmers 1: Get started after reading all things to submit homework we have to click on checkboxes but checkboxes are not clickable there i have checked in most browser
               

**In which step of the codelab can this issue be found?**
Step number. 8
![Screenshot (63)](https://user-images.githubusercontent.com/47867206/81463540-da9deb00-91d7-11ea-9a9e-cbda848c7c28.png)

**Versions**
I am using 2020.1 version

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
