### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by rajnicant** [google-developer-training/kotlin-bootcamp#34]
**Describe the problem**
Options in the questionsare not selectablr 

**In which step of the codelab can this issue be found?**
session 1 step 8.

**Steps to reproduce?**
Just go through the process

**Versions**
Lastest

**Additional information**
NO

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
