### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by sarathgoli** [google-developer-training/kotlin-bootcamp#35]
**Describe the problem**
I'm not able to select the choices in assigments

**In which step of the codelab can this issue be found?**
Step number 8 week 2 and in week 1 also

**Steps to reproduce?**
What are the steps to reproduce the problem?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
