### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by Vimaljeet** [google-developer-training/kotlin-bootcamp#36]
**Describe the problem**
The back button the the codelabs div is slight close to the mid div, as compared to the next button.

**In which step of the codelab can this issue be found?**
Step number. all the steps shows the same design issue.

**Steps to reproduce?**
just change the back button and inner div css, that would probably work.

**Versions**
runtime version-11.0.6

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by Vimaljeet** [comment]
Google has always been inspired me with their perfection and consistency of their designs. Please correct this.

**Comment by GeneAndGoogle** [comment]
The codelab tool is being updated and this issue may be addressed then.
