### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by Amrit0786** [google-developer-training/kotlin-bootcamp#37]
**Describe the problem**
The example of Aquarium Class in Java :
public class Aquarium {

   private int mTemperature;

   public Aquarium() { }

   public int getTemperature() {
       return mTemperature;
   }

   public void setTemperature(int mTemperature) {
       this.mTemperature = mTemperature;
   }

   @Override
   public String toString() {
       return "Aquarium{" +
               "mTemperature=" + mTemperature +
               '}';
   }
}
 will not produce the kotlin equivalent given there as the java implementation also consists of toString method. And by default a class in kotlin doesn't consist of a toString method unless it is a data class
. 
**In which step of the codelab can this issue be found?**
<img width="981" alt="Screenshot 2020-05-09 at 5 18 18 PM" src="https://user-images.githubusercontent.com/11272178/81472962-21f89b80-9219-11ea-9bef-abc4336c014d.png">

Kotlin Bootcamp for Programmers 1: Get started

**Steps to reproduce?**
What are the steps to reproduce the problem?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Thanks for the report. Fixed.

**Comment by Amrit0786** [comment]
class keyword is missing in the latest change. It should be **data class Aquarium (var temperature: Int = 0)** and not just **data Aquarium (var temperature: Int = 0)**
