### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by Vyshnav-KS** [google-developer-training/kotlin-bootcamp#39]
**Describe the problem**
I can"t check the check box.

**In which step of the codelab can this issue be found?**
1st lesson
8th step

**Steps to reproduce?**
What are the steps to reproduce the problem?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
