### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by gmb55** [google-developer-training/kotlin-bootcamp#4]
**Describe the problem**
Types.

In example no. 4 you use val b2, but below you use reference to b1 

**In which step of the codelab can this issue be found?**
Kotlin Bootcamp for Programmers 2: Kotlin basics
4. Assign a Byte value to variables of different types.
https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-basics/#1

`val **b2**: Byte = 1 // OK, literals are checked statically
println(b2)
⇒ 1

val i1: Int = **b1**
⇒ error: type mismatch: inferred type is Byte but Int was expected

val i2: String = **b1**
⇒ error: type mismatch: inferred type is Byte but String was expected

val i3: Double = **b1**
⇒ error: type mismatch: inferred type is Byte but Double was expected`

**Versions**
11.0.3

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Fixed.
