### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by jaiswalk008** [google-developer-training/kotlin-bootcamp#40]
**Describe the problem**
Unable to mark the answer in the homework task.

**In which step of the codelab can this issue be found?**
Homework.

**Steps to reproduce?**
just by enabling the mark option?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
