### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by anusatya-choudhary** [google-developer-training/kotlin-bootcamp#41]
**Describe the problem**
A clear and concise description of what the problem is.
The select options in the homework are not working.
**In which step of the codelab can this issue be found?**
Step number.
8
**Steps to reproduce?**
What are the steps to reproduce the problem?
0
**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**
Link - "https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-introduction/#7"
**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
