### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by Keshav1802** [google-developer-training/kotlin-bootcamp#42]
**Describe the problem**
Getting the error in lesson 3 functions

**In which step of the codelab can this issue be found?**
Step number. task 4

**Steps to reproduce?**
At the end the full program is given i have tried to copy paste the program also but it showed error

**Versions**
intellijidea 2020.1.1(community edition)
![error kotlin!!!!](https://user-images.githubusercontent.com/56951340/81825776-ab2f0b80-9554-11ea-8eea-763caeb6c240.jpg)

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Be sure you replace _all_ of the existing code with the final version.

**Comment by Keshav1802** [comment]
i have replaced the existing code with the final version but then also error is coming.
