### ISSUE TITLE
Kotlin Bootcamp issue: try.kotlinlang.org is obsolete 

### ISSUE THREAD

**Issue by chinmaykunkikar** [google-developer-training/kotlin-bootcamp#43]
**Problem**
[try.kotlinlang.org](https://try.kotlinlang.org/) is obsolete and is replaced with [play.kotlinlang.org](https://play.kotlinlang.org/) instead.

**In which step of the codelab can this issue be found?**
This is found in every "Learn More" section of all the lessons under the topic "Kotlin tutorials".

**Steps to reproduce?**
Visit any codelab under [Kotlin Bootcamp course](https://codelabs.developers.google.com/kotlin-bootcamp/) and go to the "Learn more" section.

**Versions**
Not Applicable

**Additional information**
Not Applicable

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Thanks for the report. Updated the links.
