### ISSUE TITLE
Kotlin Bootcamp issue: String concatenation used instead of string template

### ISSUE THREAD

**Issue by chinmaykunkikar** [google-developer-training/kotlin-bootcamp#44]
**Describe the problem**
In the codelab of [Functions](https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-functions) under the task [Get started with filters](https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-functions/#5), the first three code snippets under the topic *Step 2: Compare eager and lazy filters* use String concatenation instead of regular Kotlin string templates.

<details>
<summary>Examples</summary>

> `println("eager: " + eager)`

> `println("filtered: " + filtered)`

> `println("new list: " + newList)`
</details>

When I enter these snippets in IDEA, it suggests this -
> Convert concatenation to template

**In which step of the codelab can this issue be found?**
Step number 2 in: [Functions/Get started with filters](https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-functions/#5). 

**Steps to reproduce?**
Enter the following code snippet in `main()` function in IDEA:
``` kotlin
    val filtered = decorations.asSequence().filter { it[0] == 'p' }
    println("filtered: " + filtered) // the issue line
```

<details>
<summary>You will see this</summary>

![Convert concatenation to template](https://user-images.githubusercontent.com/6230769/81857683-37a2f380-9580-11ea-924a-a8d414ded571.png)

</details>

**Versions**
Community 2020.1.1
Build #IC-201.7223.91

**Additional information**
Not applicable
**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Thanks for the report. Updated the code.
