### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by sciduck** [google-developer-training/kotlin-bootcamp#47]
**Describe the problem**
The tick boxes in the homework section do not work. Or are they not supposed to? 

**In which step of the codelab can this issue be found?**
8

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
> Note: Because of the current limitations of codelabs, the quizzes in these codelabs are not interactive.
