### ISSUE TITLE
Kotlin Bootcamp issue: Step 2

### ISSUE THREAD

**Issue by gmb55** [google-developer-training/kotlin-bootcamp#5]
**Describe the problem**
You use two times a poitner 4. : 
3. Select toByte() from the list, then print the variable.
**4.** Assign a Byte value to variables of different types.
**4.** For the assignments that returned errors, try casting them instead.
5. To make long numeric constants more readable, Kotlin allows you to place underscores in the numbers, where it makes sense to you.

**In which step of the codelab can this issue be found?**
 2: Kotlin basics
Step 2: Practice using types
https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-basics/#1 

**Versions**
11.0.3

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Fixed.
