### ISSUE TITLE
Kotlin Bootcamp issue: 

### ISSUE THREAD

**Issue by yk7-yash** [google-developer-training/kotlin-bootcamp#55]
**Describe the problem**
A clear and concise description of what the problem is.
I can't select a option in the answers section

**In which step of the codelab can this issue be found?**
Step number.
Step-8

**Steps to reproduce?**
What are the steps to reproduce the problem?

**Versions**
What version of IntelliJ IDEA are you using?

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
See #18
