### ISSUE TITLE
Kotlin Bootcamp issue: 3: Functions, 4. Task: Step 1: 

### ISSUE THREAD

**Issue by gmb55** [google-developer-training/kotlin-bootcamp#7]
**Describe the problem**
In point 1. Write a function called feedtheFish()
Function name should be feedTheFish()

**In which step of the codelab can this issue be found?**
 Step 1: 
[link](https://codelabs.developers.google.com/codelabs/kotlin-bootcamp-functions/#3)

**Versions**
11.0.3

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Fixed.
