### ISSUE TITLE
Kotlin Bootcamp issue: typographical errors

### ISSUE THREAD

**Issue by bmwild** [google-developer-training/kotlin-bootcamp#8]
**Describe the problem**
Firstly, there are two point 5's under Step 2, so the second should be labelled as point 6.

Secondly, in the demonstrated code, "println(Arrays.toString(array))" should be "println(java.util.Arrays.toString(array))".

**In which step of the codelab can this issue be found?**

Step 2, second point 5 of 5. Task: Explore arrays, lists, and loops of Kotlin Bootcamp for Programmers 2: Kotlin basics.

**Versions**
What version of IntelliJ IDEA are you using?

IntelliJ IDEA 2019.2.2 (Community Edition)
Build #IC-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-30deepin-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 837M
Cores: 8
Registry: 
Non-Bundled Plugins: 

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Fixed.
