### ISSUE TITLE
Kotlin Bootcamp issue: Do not put a space before an opening parenthesis in a method declaration or method call.

### ISSUE THREAD

**Issue by t-kl** [google-developer-training/kotlin-bootcamp#9]
**Describe the problem**
Kotlin Bootcamp for Programmers 1: Get started
In chapter "7. Learn more" a link to the [Kotlin coding conventions](https://kotlinlang.org/docs/reference/coding-conventions.html) is provided.
In the section _Horizontal whitespace_ it is stated:
> Do not put a space before an opening parenthesis in a primary constructor declaration, method declaration or method call.

But it "5. Task: Create Hello Kotlin" the example uses a space before the method name:
```
fun printHello () {
    println ("Hello World")
}
```

Totally nitpick but you still may want to fix that.
Because it's the first example a newcomer sees and it doesn't adhere to the _Kotlin_ coding conventions.

**In which step of the codelab can this issue be found?**
5. Task: Create Hello Kotlin

**Versions**
IntelliJ IDEA 2019.2.3 (Community Edition)
Build #IC-192.6817.14, built on September 24, 2019

**Additional information**

**codelab:** kotlin-bootcamp

**Comment by GeneAndGoogle** [comment]
Fixed.
